# Generated by Django 4.0.1 on 2022-02-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_post_postlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logopost'),
        ),
        migrations.DeleteModel(
            name='PostLogo',
        ),
    ]
