# Generated by Django 4.0.1 on 2022-02-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_post_imagen_delete_postlogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='logo',
        ),
    ]
